#!/bin/bash
docker pull lorketz/image_final-python:latest
docker stop python_server || true
docker rm python_server || true
docker run -d -p 5000:5000 --name python_server lorketz/image_final-python:latest
